import sys
from pathlib import Path

# Get the project root
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from models.distributions import PoissonDistribution
from utils.data_loader import SparePart
from typing import List


# These are examples generated by DeepSeek for the files in project
class ItemApproach:
    """Individual item optimization approach."""
    
    @staticmethod
    def stock_level(part: SparePart, S) -> int:
        """Find safe stock level """
        lambd_leadtime = part.mean_demand * part.repair_time
        
        return PoissonDistribution.cdf(S, lambd_leadtime)
            
    
    @staticmethod
    def find_best_stock_level(part: SparePart, target_fill_rate: float = 0.9) -> int:
        """Find safe stock level to achieve target fill rate."""
        S = 1
        while True:
            
            prob = ItemApproach.stock_level(part, S)
            if prob > target_fill_rate:
                return S
            else:
                S += 1
    
    @staticmethod
    def aggregated_service_level(parts:List[SparePart], levels:List[int]) -> float:
        total_sum = 0
        total_rate = 0
        for part in parts:
            total_rate += part.mean_demand
        for i in range(len(parts)):
            total_sum += parts[i].mean_demand/total_rate * ItemApproach.stock_level(parts[i], levels[parts[i].part_id])
        return total_sum
    
    @staticmethod
    def calculate_total_cost(part: SparePart, S: int) -> float:
        """Calculate expected total cost for given stock level."""
        
        cost = part.unit_cost * S
        
        return cost