import sys
from pathlib import Path

# Get the project root
project_root = Path(__file__).parent.parent
sys.path.insert(0, str(project_root))

from models.distributions import PoissonDistribution
from utils.data_loader import SparePart


# These are examples generated by DeepSeek for the files in project
class SystemApproach:
    """multiple items optimization approach."""
    
    @staticmethod
    def find_safe_stock_level(part: SparePart, target_fill_rate: float = 0.9) -> int:
        """Find safe stock level to achieve target fill rate."""
        S = 1
        while True:
            lambd_leadtime = part.mean_demand * part.repair_time
            
            prob = PoissonDistribution.cdf(S, lambd_leadtime)
            if prob > target_fill_rate:
                return S
            else:
                S += 1
    